#!/bin/sh

defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 1.5
defaults write -g com.apple.mouse.scaling -1
# defaults write com.apple.dock expose-animation-duration -float 0.1
# defaults write .GlobalPreferences com.apple.scrollwheel.scaling -1

killAll Finder && killAll Dock

