#!/bin/sh

if ! command -v pandoc&> /dev/null
then
	echo semd requires the pandoc command/library to compile md to html
	echo you can install it with homebrew and most package mana
	exit
fi

if ! command -v firefox &> /dev/null
then
	echo semd requires a cli for firefox
	exit
fi

pandoc $1 --from=gfm -t html -o /tmp/semdtmp.html
firefox --new-window file:///tmp/semdtmp.html
