#!/bin/sh

if ! command -v pandoc&> /dev/null
then
	echo semd requires the pandoc command/library to compile md to html
	echo you can install it with homebrew and most package mana
	exit
fi

if ! command -v firefox &> /dev/null
then
	echo semd requires a cli for firefox
	exit
fi

# -f markdown-implicit_figures
#pandoc --mathjax -t html $1 -s -o /tmp/semdtmp.html
if [ -z "${out}" ]; then
	out="./semd.pdf"
else
	out=$2
fi

pandoc $1 --mathjax -f markdown-implicit_figures -o $out
# pandoc $1 --from=gfm -t html -o /tmp/semdtmp.html
# firefox --new-tab file:///tmp/semdtmp.html
