#!/bin/sh

DIR="$HOME/.task"

openTask(){
# FIXME this is way too slow
	if [ -d "$DIR/.git" ]; then
		git -C ${DIR} pull 
	fi
	vi -c "set ft=markdown" "${1}"
	closeTask $1 -&
}

closeTask(){
	if [ -d "$DIR/.git" ]; then
		if git -C $DIR add ${1} &> /dev/null && git -C $DIR commit -m "$(date)" &> /dev/null  && git -C ${DIR} push &> /dev/null ; then
			echo pushed to remote
		else
			echo failed to push to remote
		fi
	fi
}


if [ ! -d "$DIR" ]; then
	echo "Task was never used ..."
	echo "Preparing environment for task"
	sleep 2
	mkdir -p $DIR
fi

if [ -z ${1} ]; then 
	openTask "${DIR}/task"
	exit
fi

if [ "$1" = "ls" ]; then
	echo "\n--- YOUR TASKS ---\n"
	ls -l "${DIR}"
	echo "\n"
	exit
fi

if [ "$1" = "rm" ]; then
	rm "${DIR}/${2}"
	if [ -d "${DRI}/.git" ]; then
		if git -C ${DIR} rm ${2} && git -C ${DIR} commit -m "removing $2 $(date)" && git -C ${DIR} push ; then
			echo git delete sync successfull
		else
			echo git delete sync failed
		fi
	fi
	echo "Deleting ${2}"
	exit
fi

if [ "$1" = "-g" ]; then
	echo "This operation will overwirte you current tasks"
	echo "We are making a backup in ~/taskBakup"
	sleep 5
	if mv ~/.task ~/taskBackup$(date|tr '\ ' '_') && git clone $2 ~/.task ; then
		echo git sync was successfull
		git -C ${DIR} add *
		git -C ${DIR} commit -m "sync with $(hostname)"
		git -C ${DIR} push
		exit
	fi
	echo git sync failed
	exit
fi

if [ "$1" = "--help" ]; then
	echo task [command] [task_name]
	echo
	echo enter name of new task or existing task to modify
	echo ls:        list available tasks
	echo rm [task]: removes a task
	echo -g [url]:  will sync up with indicated git remote
	echo --help:    display this message
	echo
	exit
fi

openTask "${DIR}/${1}"
